name: Post ES

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 18 * * *"   # 18:05 UTC (Spain 19:05)
    - cron: "5 1 * * *"    # 01:05 UTC (Mexico City 19:05)
    - cron: "5 22 * * *"   # 22:05 UTC (Buenos Aires 19:05)



concurrency:
  group: post-es
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    env:
      LANG: es
      MAX_UPLOADS: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm install --no-audit --no-fund
      - name: Upload to YouTube
        env:
          YT_CLIENT_ID:     ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN_ES }}
        run: node scripts/youtube_upload.js --lang="$LANG" --max="$MAX_UPLOADS"
      - name: Commit moves
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add videos/$LANG/sent/* videos/$LANG/queue/* 2>/dev/null || true
          git commit -m "post(${LANG}): move to sent" || echo "nothing to commit"
          git push || true
