name: Post JA from Stock

on:
  workflow_dispatch: {}
  schedule:
    - cron: '5 15 * 3-10 *'
    - cron: '5 16 * 11,12 *'
    - cron: '5 16 * 1,2 *'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      LANG: ja
      MAX_UPLOADS: ${{ github.event.inputs.max || '2' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Upload to YouTube
        env:
          YT_CLIENT_ID:     ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN_JA }}
        run: node scripts/youtube_upload.js --lang="$LANG" --max="$MAX_UPLOADS"

      - name: Commit moves
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add videos/$LANG/sent/* videos/$LANG/queue/* 2>/dev/null || true
          git commit -m "post(${LANG}): move to sent" || echo "nothing to commit"
          git push || true
