name: Restock all languages

on:
  schedule:
    - cron: "30 16 * * *"   # 01:30 JST
  workflow_dispatch: {}

jobs:
  restock:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    env:
      TARGET_STOCK: "12"                 # ← 目標在庫/言語（調整OK）
      LANGS: "en,ja"                     # まずは en/ja。増やす時はここを追加
      DURATION: "10"
      BG: assets/bg/loop.mp4
      AUDIO: assets/bgm/ambient01.mp3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - name: Install ffmpeg & deps
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          npm ci

      # ① ENマスターを seeds から生成（不足分に応じて必要回数）
      - name: Ensure EN YAML (generate from seeds)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          NEED=0
          CUR_EN=$(ls -1 data/en/*.yaml 2>/dev/null | wc -l)
          # ENのYAMLは日別で増やすより1ファイルに複数entriesでもOKなので、とりあえず1回生成
          node scripts/seed_to_yaml.js --count=6 || true
          echo "generated EN YAML (see data/en)"

      # ② 翻訳（ENがあればJAを作る）
      - name: Translate EN -> JA (and others later)
        if: always()
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # 直近のEN YAMLファイル名を拾って翻訳
          LATEST=$(ls -1t data/en/*.yaml | head -n1)
          if [ -n "$LATEST" ]; then
            DATE=$(basename "$LATEST" .yaml)
            node scripts/translate_yaml.js --date="$DATE" --langs=ja
          fi

      # ③ 言語ごとに在庫を見て、不足分だけレンダして queue に積む
      - name: Render to queues
        run: |
          IFS=',' read -ra LGS <<< "${{ env.LANGS }}"
          LATEST=$(ls -1t data/en/*.yaml | head -n1)
          DATE=$(basename "$LATEST" .yaml)
          for L in "${LGS[@]}"; do
            CUR=$(ls -1 videos/$L/queue/*.mp4 2>/dev/null | wc -l)
            NEED=$(( ${{ env.TARGET_STOCK }} - CUR ))
            echo "$L queue=$CUR need=$NEED"
            if [ "$NEED" -gt 0 ]; then
              # render_video.js は entries を順に複数本出力するので、そのまま使う
              node scripts/render_video.js --lang="$L" --date="$DATE" \
                  --dur="${{ env.DURATION }}" --bg="${{ env.BG }}" --audio="${{ env.AUDIO }}"
            fi
          done

      - name: Commit stock
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add videos/**/queue/* data/** || true
          git commit -m "restock: add videos & yamls" || echo "nothing to commit"
          git push || true
